### ISSUE TITLE
log: Export function without context

### ISSUE THREAD

**Issue by Xuanwo** [pengsrc/go-utils#1]

**Comment by pengsrc** [comment]
I’ll do it ASAP.

**Comment by pengsrc** [comment]
Added a wrapper structure called `ContextFreeLogger` in commit https://github.com/pengsrc/go-shared/commit/7ccf0f9ba223795098bf41a9ba187b0720ec5c27 to provide similar interface like https://golang.org/pkg/log/.

**Comment by Xuanwo** [comment]
LGTM
