### ISSUE TITLE
Use semantic versioning 2.0.0

### ISSUE THREAD

**Issue by Xuanwo** [pengsrc/go-utils#4]
ref: https://semver.org/

**Comment by pengsrc** [comment]
What's the problem?

**Comment by Xuanwo** [comment]
Changes like this: https://github.com/pengsrc/go-shared/commit/4ac6c7f34d751b23e51c0bb573dc5f6658c74590#diff-f7845a7f2a431b2c49c94215cf857df7R71 will break user's application.

Maybe we need to add a changelog and follow the semantic version rules.

**Comment by pengsrc** [comment]
As quoted from https://semver.org/#spec-item-4. So, that's just alright.

> 4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

The changelog will be added in later versions. And once the documentation is ready, there'll be the v1.0.0.

**Comment by Xuanwo** [comment]
That's fine.
